// DISPLAY ACTIONS
const CHANGE_DISPLAY = 'CHANGE_DISPLAY';

// TIMER ACTIONS
const PLAY = 'PLAY';
const PAUSE = 'PAUSE';
const RESET = 'RESET';

// CONFIG ACTIONS
const INCREMENT_BREAK_LENGTH = 'INCREMENT_BREAK_LENGTH';
const DECREMENT_BREAK_LENGTH = 'DECREMENT_BREAK_LENGTH';
const INCREMENT_SESSION_LENGTH = 'INCREMENT_SESSION_LENGTH';
const DECREMENT_SESSION_LENGTH = 'DECREMENT_SESSION_LENGTH';

export {
  CHANGE_DISPLAY,
  PLAY,
  PAUSE,
  RESET,
  INCREMENT_BREAK_LENGTH,
  DECREMENT_BREAK_LENGTH,
  INCREMENT_SESSION_LENGTH,
  DECREMENT_SESSION_LENGTH
};