// DISPLAY ACTIONS
const CHANGE_DISPLAY = 'CHANGE_DISPLAY';
const RESET_DISPLAY = 'RESET_DISPLAY';

// TIMER ACTIONS
const PLAY_TIMER = 'PLAY_TIMER';
const PAUSE_TIMER = 'PAUSE_TIMER';

// CONFIG ACTIONS
const INCREMENT_BREAK_LENGTH = 'INCREMENT_BREAK_LENGTH';
const DECREMENT_BREAK_LENGTH = 'DECREMENT_BREAK_LENGTH';
const INCREMENT_SESSION_LENGTH = 'INCREMENT_SESSION_LENGTH';
const DECREMENT_SESSION_LENGTH = 'DECREMENT_SESSION_LENGTH';
const RESET_CONFIG = 'RESET_CONFIG';

const actions = {
  CHANGE_DISPLAY,
  RESET_DISPLAY,
  PLAY_TIMER,
  PAUSE_TIMER,
  INCREMENT_BREAK_LENGTH,
  DECREMENT_BREAK_LENGTH,
  INCREMENT_SESSION_LENGTH,
  DECREMENT_SESSION_LENGTH,
  RESET_CONFIG
}

export default actions;